In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_credit=pd.read_csv(r"C:\Users\khush\OneDrive\Desktop\Python Dataset\Credit_Risk_data.csv")
data_credit.head() 

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
data_credit=data_credit.drop(['Loan_ID'],axis=1)
data_credit

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         NaN             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [4]:
data_credit.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
data_credit.Gender=data_credit.Gender.fillna("Female")
data_credit.Married=data_credit.Married.fillna("No")
data_credit.Dependents=data_credit.Dependents.fillna("3+")
data_credit.Self_Employed=data_credit.Self_Employed.fillna("Yes")
data_credit.LoanAmount=data_credit.LoanAmount.fillna(data_credit.LoanAmount.median())
data_credit.Loan_Amount_Term=data_credit.Loan_Amount_Term.fillna(12.0)
data_credit.Credit_History=data_credit.Credit_History.fillna(0.0)

In [6]:
data_credit.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [7]:
data_credit.Gender.replace({"Male":0,"Female":1},inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [9]:
data_credit.Married=le.fit_transform(data_credit.Married)
data_credit.Dependents=le.fit_transform(data_credit.Dependents)
data_credit.Education=le.fit_transform(data_credit.Education)
data_credit.Self_Employed=le.fit_transform(data_credit.Self_Employed)
data_credit.Property_Area=le.fit_transform(data_credit.Property_Area)
data_credit.Loan_Status=le.fit_transform(data_credit.Loan_Status)

In [10]:
x=data_credit.iloc[:,0:-1]
y=data_credit.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [13]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((491, 11), (123, 11), (491,), (123,))

# Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [15]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
dt_p=dt.predict(x_test)
dt_p

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0])

In [17]:
from sklearn.metrics import confusion_matrix
dt_c=confusion_matrix(y_test,dt_p)
dt_c

array([[26, 19],
       [22, 56]], dtype=int64)

In [18]:
dt_ac=dt_c.diagonal().sum()/dt_c.sum()*100
dt_ac

66.66666666666666

In [19]:
dt.feature_importances_

array([0.03295553, 0.01502645, 0.05382713, 0.02606753, 0.0041613 ,
       0.24272284, 0.11604735, 0.23787436, 0.05600077, 0.18939607,
       0.02592067])

In [20]:
df=pd.DataFrame(dt.feature_importances_)
#df
df=df.rename(columns={df.columns[0]:"Score"})
df

Score
0   0.032956
1   0.015026
2   0.053827
3   0.026068
4   0.004161
5   0.242723
6   0.116047
7   0.237874
8   0.056001
9   0.189396
10  0.025921

In [21]:
df1=pd.DataFrame({"Feature_Score":list(dt.feature_importances_),"columns":list(data_credit.iloc[:,:-1].columns)})
df1

Feature_Score            columns
0        0.032956             Gender
1        0.015026            Married
2        0.053827         Dependents
3        0.026068          Education
4        0.004161      Self_Employed
5        0.242723    ApplicantIncome
6        0.116047  CoapplicantIncome
7        0.237874         LoanAmount
8        0.056001   Loan_Amount_Term
9        0.189396     Credit_History
10       0.025921      Property_Area

In [22]:
data_credit1=data_credit.drop(["Gender","Married","Dependents","Education","Self_Employed","Loan_Amount_Term","Property_Area"],axis=True)
data_credit1.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Credit_History  Loan_Status
0             5849                0.0       128.0             1.0            1
1             4583             1508.0       128.0             1.0            0
2             3000                0.0        66.0             1.0            1
3             2583             2358.0       120.0             1.0            1
4             6000                0.0       141.0             1.0            1

In [23]:
n_x=data_credit1.iloc[:,:-1]
n_y=data_credit1.iloc[:,-1]

In [24]:
xtr,xte,ytr,yte=train_test_split(n_x,n_y,test_size=0.2,random_state=100)
xtr.shape,xte.shape,ytr.shape,yte.shape

((491, 4), (123, 4), (491,), (123,))

In [25]:
dt.fit(xtr,ytr)

DecisionTreeClassifier()

In [26]:
p1=dt.predict(xte)

In [27]:
c1=confusion_matrix(yte,p1)
c1

array([[22, 26],
       [22, 53]], dtype=int64)

In [28]:
a1=c1.diagonal().sum()/c1.sum()*100
a1

60.97560975609756

# Prepare RF,LG,KNN,SVM,NB

# RandomForest

In [29]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [30]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [31]:
rf_p=rf.predict(x_test)

In [32]:
rf_c=confusion_matrix(y_test,rf_p)
rf_c

array([[23, 22],
       [10, 68]], dtype=int64)

In [33]:
rf_ac=rf_c.diagonal().sum()/rf_c.sum()*100
rf_ac

73.98373983739837

In [34]:
rf.feature_importances_

array([0.02609674, 0.02721287, 0.05568708, 0.02844913, 0.0208246 ,
       0.21227929, 0.14252349, 0.20357346, 0.05756737, 0.17385985,
       0.0519261 ])

In [35]:
df2=pd.DataFrame({"Feature_Score":list(rf.feature_importances_),"columns":list(data_credit.iloc[:,:-1].columns)})
df2

Feature_Score            columns
0        0.026097             Gender
1        0.027213            Married
2        0.055687         Dependents
3        0.028449          Education
4        0.020825      Self_Employed
5        0.212279    ApplicantIncome
6        0.142523  CoapplicantIncome
7        0.203573         LoanAmount
8        0.057567   Loan_Amount_Term
9        0.173860     Credit_History
10       0.051926      Property_Area

In [36]:
data_credit3=data_credit.drop(["Gender","Married","Education","Self_Employed","Loan_Amount_Term","Property_Area"],axis=True)
data_credit3.head()

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  Credit_History  \
0           0             5849                0.0       128.0             1.0   
1           1             4583             1508.0       128.0             1.0   
2           0             3000                0.0        66.0             1.0   
3           0             2583             2358.0       120.0             1.0   
4           0             6000                0.0       141.0             1.0   

   Loan_Status  
0            1  
1            0  
2            1  
3            1  
4            1

In [37]:
n_x1=data_credit1.iloc[:,:-1]
n_y1=data_credit1.iloc[:,-1]

In [38]:
xtr,xte,ytr,yte=train_test_split(n_x1,n_y1,test_size=0.2,random_state=100)
xtr.shape,xte.shape,ytr.shape,yte.shape

((491, 4), (123, 4), (491,), (123,))

In [39]:
rf.fit(xtr,ytr)

RandomForestClassifier()

In [40]:
rf_p=rf.predict(xte)

In [41]:
c1=confusion_matrix(yte,p1)
c1

array([[22, 26],
       [22, 53]], dtype=int64)

In [42]:
rf_ac=c1.diagonal().sum()/c1.sum()*100
rf_ac

60.97560975609756

# Method-3 (Chi-Square Test)

In [43]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [44]:
chiTest=SelectKBest(score_func=chi2,k="all")

In [45]:
c=chiTest.fit(data_credit.iloc[:,:-1],data_credit.iloc[:,-1])

In [46]:
c2=c.scores_
c2

array([3.15654028e-01, 1.53429184e+00, 9.69620727e-03, 3.54050246e+00,
       1.71493480e-02, 9.39049635e+01, 1.13420416e+04, 3.28216554e+01,
       5.18707315e-01, 2.60148043e+01, 3.77837464e-01])

In [47]:
c3=pd.DataFrame(c2)
c3=c3.rename(columns={c3.columns[0]:"score"})
c3

score
0       0.315654
1       1.534292
2       0.009696
3       3.540502
4       0.017149
5      93.904964
6   11342.041603
7      32.821655
8       0.518707
9      26.014804
10      0.377837

In [48]:
c4=pd.DataFrame({"Feature_imp":list(c2),"columns":list(data_credit.iloc[:,:-1].columns)})
c4

Feature_imp            columns
0       0.315654             Gender
1       1.534292            Married
2       0.009696         Dependents
3       3.540502          Education
4       0.017149      Self_Employed
5      93.904964    ApplicantIncome
6   11342.041603  CoapplicantIncome
7      32.821655         LoanAmount
8       0.518707   Loan_Amount_Term
9      26.014804     Credit_History
10      0.377837      Property_Area

In [49]:
data_credit5=data_credit.drop(["Gender","Married","Dependents","Education","Self_Employed","Loan_Amount_Term","Property_Area"],axis=True)
data_credit5.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Credit_History  Loan_Status
0             5849                0.0       128.0             1.0            1
1             4583             1508.0       128.0             1.0            0
2             3000                0.0        66.0             1.0            1
3             2583             2358.0       120.0             1.0            1
4             6000                0.0       141.0             1.0            1

In [50]:
n_x2=data_credit5.iloc[:,:-1]
n_y2=data_credit5.iloc[:,-1]

In [51]:
xtr1,xte1,ytr1,yte1=train_test_split(n_x2,n_y2,test_size=0.2,random_state=100)
xtr1.shape,xte1.shape,ytr1.shape,yte1.shape

((491, 4), (123, 4), (491,), (123,))

In [52]:
rf.fit(xtr1,ytr1)

RandomForestClassifier()

In [53]:
rf_p=rf.predict(xte1)

In [54]:
c2=confusion_matrix(yte1,rf_p)
c2

array([[20, 28],
       [12, 63]], dtype=int64)

In [55]:
r_ac=c2.diagonal().sum()/c2.sum()*100
r_ac

67.47967479674797

# Method-4 RFE(Recursive Feature Elimination)

In [56]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()

In [59]:
rfe=RFE(dtree,n_features_to_select=5)

In [60]:
rfe.fit(data_credit.iloc[:,:-1],data_credit.iloc[:,-1])

RFE(estimator=DecisionTreeClassifier(), n_features_to_select=5)

In [61]:
rfe.support_

array([False, False,  True, False, False,  True,  True,  True, False,
        True, False])

In [63]:
f1=pd.DataFrame({"feature":list(rfe.support_),"col":list(data_credit.iloc[:,:-1].columns)})

In [64]:
f1

feature                col
0     False             Gender
1     False            Married
2      True         Dependents
3     False          Education
4     False      Self_Employed
5      True    ApplicantIncome
6      True  CoapplicantIncome
7      True         LoanAmount
8     False   Loan_Amount_Term
9      True     Credit_History
10    False      Property_Area

# Extract imp columns and prepare models

# Boruta

In [65]:
d_Sonar=pd.read_csv(r"C:\Users\khush\Downloads\Sonar.csv")
d_Sonar.head()

Unnamed: 0      V1      V2      V3      V4      V5      V6      V7      V8  \
0           1  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601   
1           2  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481   
2           3  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771   
3           4  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276   
4           5  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467   

       V9  ...     V52     V53     V54     V55     V56     V57     V58  \
0  0.3109  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.3337  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.5598  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.0598  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.3564  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

      V59     V60  Class  
0  0.0090  0.0032      R  
1  0.0052  0.0044      R  
2  0.0095  0.0078      R  
3  0.0040  0.0117      R  
4  0.0107  0.0094      R  

[5 rows x 62 columns]

In [67]:
d_Sonar.shape

(208, 62)

In [68]:
import numpy as np

In [75]:
s_x=np.array(d_Sonar.iloc[:,1:-1])
s_y=np.array(d_Sonar.iloc[:,-1])

In [76]:
from boruta import BorutaPy

In [77]:
rf=RandomForestClassifier()

In [78]:
boruta_feature=BorutaPy(rf,random_state=111,max_iter=50,perc=100,verbose=2)

In [79]:
boruta_feature.fit(s_x,s_y)

Iteration: 	1 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	2 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	3 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	4 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	5 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	6 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	7 / 50
Confirmed: 	0
Tentative: 	60
Rejected: 	0
Iteration: 	8 / 50
Confirmed: 	22
Tentative: 	22
Rejected: 	16
Iteration: 	9 / 50
Confirmed: 	22
Tentative: 	22
Rejected: 	16
Iteration: 	10 / 50
Confirmed: 	22
Tentative: 	22
Rejected: 	16
Iteration: 	11 / 50
Confirmed: 	22
Tentative: 	22
Rejected: 	16
Iteration: 	12 / 50
Confirmed: 	23
Tentative: 	21
Rejected: 	16
Iteration: 	13 / 50
Confirmed: 	23
Tentative: 	21
Rejected: 	16
Iteration: 	14 / 50
Confirmed: 	23
Tentative: 	21
Rejected: 	16
Iteration: 	15 / 50
Confirmed: 	23
Tentative: 	21
Rejected: 	16
Iteration: 	16 / 50
Confirmed: 	23
Tentative: 	18
Rejected: 	19

BorutaPy(estimator=RandomForestClassifier(n_estimators=1000,
                                          random_state=RandomState(MT19937) at 0x21A519A9740),
         max_iter=50, random_state=RandomState(MT19937) at 0x21A519A9740,
         verbose=2)

In [80]:
boruta_feature.support_

array([ True, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True, False, False, False, False, False,  True,
        True, False, False,  True, False, False, False,  True,  True,
        True, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
       False, False, False, False, False, False])

In [81]:
len(boruta_feature.support_)

60

In [82]:
s1_x=d_Sonar.iloc[:,1:-1]
b1=pd.DataFrame({"column":s1_x.columns,"Feature_imp":list(boruta_feature.support_)})
b1

column  Feature_imp
0      V1         True
1      V2        False
2      V3        False
3      V4         True
4      V5         True
5      V6         True
6      V7        False
7      V8        False
8      V9         True
9     V10         True
10    V11         True
11    V12         True
12    V13         True
13    V14        False
14    V15        False
15    V16         True
16    V17         True
17    V18         True
18    V19        False
19    V20         True
20    V21         True
21    V22        False
22    V23        False
23    V24        False
24    V25        False
25    V26        False
26    V27         True
27    V28         True
28    V29        False
29    V30        False
30    V31         True
31    V32        False
32    V33        False
33    V34        False
34    V35         True
35    V36         True
36    V37         True
37    V38        False
38    V39        False
39    V40        False
40    V41        False
41    V42        False
42    V43         True
43    V44         True
44    V45         True
45    V46         True
46    V47         True
47    V48         True
48    V49         True
49    V50        False
50    V51         True
51    V52         True
52    V53        False
53    V54        False
54    V55        False
55    V56        False
56    V57        False
57    V58        False
58    V59        False
59    V60        False